# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# TODO: switch to actual githook script, failed build because of difference between mypy and mirror
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
        exclude: .*\.md
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
