name: deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  pypi_release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Publish to pypi
      env:
        POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
        POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.uhabits_converter_pypi_api_token }}
      run: |
        poetry publish --build
